const PROCESS_CATEGORIES = [
  {id:"recebimento", label:"Recebimento",              cor:"#3ee0d6", ordem:1},
  {id:"armazenagem", label:"Armazenagem",              cor:"#f5b301", ordem:2},
  {id:"movimentacao",label:"Movimentação entre Endereços", cor:"#8b7cf6", ordem:3},
  {id:"picking",     label:"Picking",                  cor:"#5bd97a", ordem:4},
  {id:"packing",     label:"Packing",                  cor:"#f57b5b", ordem:5},
  {id:"expedicao",   label:"Expedição",                cor:"#4fa8f0", ordem:6},
  {id:"geral",       label:"Geral / Configuração",      cor:"#93a1c4", ordem:7},
];

const TABELA_CATEGORIA = {"TGWITER": "recebimento", "TGWRXN": "recebimento", "TGWREC": "recebimento", "TGWVAE": "armazenagem", "TGWARA": "armazenagem", "TGWARM": "armazenagem", "TGWARE": "armazenagem", "TGWEXU": "armazenagem", "TGWEND": "armazenagem", "TGWAXFE": "armazenagem", "TGWAXG": "armazenagem", "TGWAXPAR": "armazenagem", "TGWAXP": "armazenagem", "TGWRFA": "armazenagem", "TGWRARM": "armazenagem", "TGWEAX": "armazenagem", "TGWEXP": "armazenagem", "TGWEXG": "armazenagem", "TGWEXL": "armazenagem", "TGWEGE": "armazenagem", "TGWFEG": "armazenagem", "TGWGEN": "armazenagem", "TGWEPA": "armazenagem", "TGWLCE": "armazenagem", "TGWTRA": "movimentacao", "TGWRAG": "movimentacao", "TGWREP": "movimentacao", "TGWTRAN": "movimentacao", "TGWUXT": "picking", "TGWITT": "picking", "TGWPTR": "picking", "TGWTEC": "picking", "TGWTDP": "picking", "TGWTAR": "picking", "TGWTTE": "picking", "TGWTTR": "picking", "TGWUSU": "picking", "TGWARS": "picking", "TGWSVAR": "picking", "TGWSXN": "picking", "TGWOND": "picking", "TGWQCS": "picking", "TGWRCS": "picking", "TGWSEP": "picking", "TGWUAS": "picking", "TGWHCT": "picking", "TGWEMPE": "picking", "TGWIES": "packing", "TGWREV": "packing", "TGWIVL": "packing", "TGWPVOL": "packing", "TGWARC": "packing", "TGWCON": "packing", "TGWNCP": "packing", "TGWUAC": "packing", "TGWICC": "packing", "TGWCOI": "packing", "TGWCOIVAL": "packing", "TGWRCON": "packing", "TGWCSER": "packing", "TGWVCC": "packing", "TGWTCX": "packing", "TGWCCX": "packing", "TGWDCA": "expedicao", "TGWFATAUTO": "expedicao", "TGWLOGFATAUTO": "expedicao", "TGWTRCD": "expedicao", "TGWPXN": "expedicao", "TGWRPL": "expedicao", "TGWRUMA": "expedicao", "TGWDEV": "expedicao", "TGWAJE": "geral", "TGWIVR": "geral", "TGWCTE": "geral", "TGWIVT": "geral", "TGWIVRSER": "geral", "TGWHAJ": "geral", "TGWENP": "geral", "TGWEST": "geral", "TGWEPL": "geral", "TGWESTVAL": "geral", "TGWAGE": "geral", "TGWCONFEMPE": "geral", "TGWEQP": "geral", "TGWXMLS": "geral", "TGWITE": "geral", "TGWLBO": "geral", "TGWLCN": "geral", "TGWMCT": "geral", "TGWMDIV": "geral", "TGWMPR": "geral", "TGWMOC": "geral", "TGWOCO": "geral", "TGWQTR": "geral", "TGWRPR": "geral", "TGWUTOK": "geral", "TGWEXPL": "geral", "TGWHAD": "geral"};
const CATEGORIA_KEYWORDS = {"recebimento": ["recebimento", "receber", "doca de entrada", "nota de entrada", "conferência de entrada", "conferencia de entrada", "xml", "danfe", "nota fiscal de entrada", "fornecedor", "compra", "chegada de mercadoria", "descarga", "agendamento de recebimento", "triagem", "cross docking", "crossdocking", "devolução de compra", "devolucao de compra"], "armazenagem": ["armazenagem", "armazenar", "endereço", "endereco", "endereçamento", "enderecamento", "rua", "prédio", "predio", "nível", "nivel", "apartamento", "picking", "pulmão", "pulmao", "porta-palete", "porta palete", "blocado", "regra de armazenagem", "área de armazenagem", "area de armazenagem", "mascara de endereço", "máscara de endereço", "cadastro massivo", "alocação", "alocacao", "endereço especial", "garantia", "avaria", "perda", "sobra", "divergência", "divergencia"], "movimentacao": ["transferência", "transferencia", "movimentação entre endereços", "movimentacao entre enderecos", "reabastecimento", "realocação", "realocacao", "troca de endereço", "troca de endereco", "movimentação pró ativa", "movimentacao pro ativa", "transito", "trânsito", "completar endereço", "completar endereco", "rebalanceamento"], "picking": ["picking", "separação", "separacao", "onda", "separador", "tarefa", "corte", "corte de separação", "corte de separacao", "coletor", "rf", "aptidão", "aptidao", "equipamento", "paleteira", "empilhadeira", "roteirização", "roteirizacao", "wave", "separação agrupada", "separacao agrupada", "curva pqr", "empenho"], "packing": ["packing", "conferência", "conferencia", "conferente", "etiqueta", "volume", "embalagem", "caixa", "checkout", "validação", "validade", "série", "serie", "conferência cega", "conferencia cega", "romaneio de volume", "formação de volume", "formacao de volume", "peso do volume"], "expedicao": ["expedição", "expedicao", "doca de saída", "doca de saida", "ordem de carga", "romaneio", "transportadora", "carregamento", "envio", "nota fiscal de saída", "nota fiscal de saida", "faturamento automático", "faturamento automatico", "balcão", "balcao", "tratamento de falta de estoque", "corte na expedição", "corte na expedicao", "devolução de venda", "devolucao de venda"], "geral": ["estoque", "inventário", "inventario", "ajuste de estoque", "preferências da empresa", "preferencias da empresa", "configuração", "configuracao", "utilizawms", "top", "cadastro de equipamento", "usuário", "usuario", "token", "ocorrência", "ocorrencia", "motivo de parada"]};
